# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bf44833e144a24af6b47297b5c247484d4b6f1dbded78f74eca98f48f8581fcfbd898f2be94a85fef3781361fcfb6b45c0298de042ed4eca46e068f1d61a368

test:
  secret_key_base: d966563fdafabde42e81d1883b0f0126818c766d3ff091725bf032b0fc3512867ab0e48ed6ea244becccf693d08da2ceb892a191864311acbe549652253b27a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
